efabless/mpw_precheck

consistency_checks/consistency_checker.py, drc_checks/gds_drc_checker.py, open_shuttle_mpw_prechecker.py, utils/utils.py
reworking prints for patch processing
=> Reworking prints

base_checks/check_license.py, base_checks/check_yaml.py, consistency_checks/consistency_checker.py, consistency_checks/utils/doc_utils.py, drc_checks/gds_drc_checker.py, open_mpw_prechecker.py, utils/utils.py
=> Spdx checks

base_checks/check_license.py
Items are directories (like .git), file name (like LICENSE) and
extensions (like .gds)
It might be necessary to allow user to ignore also files when they
are generated.
=> check_license.py: add a list of items to be ignored.

consistency_checks/consistency_checker.py, drc_checks/gds_drc_checker.py
- Clearer print messages for magic failures. 
- Pointers to the magic log files from the full_log.log.
- Catch invalid GDSes with `used but not defined` errors.
=> Magic messages update

consistency_checks/consistency_checker.py, drc_checks/gds_drc_checker.py
- Reverted the tweaks that were done to get a false GDS Hierarchy pass.
- Re-enabled Pin checks (ignoring the power pins for now until they are represented in the netlist).
=> Disabled checks

dependencies/Dockerfile, drc_checks/magic_drc_check.tcl, drc_checks/magic_drc_to_rdb.py, drc_checks/run_drc_checks.sh
- abstract SRAMs inside user_project_wrapper.
- Update Magic version to mpw-one-a version.
- add magic.drc to magic.rdb conversion script for Klayout display.
=> Drc updates

consistency_checks/utils/doc_utils.py
- Introduce IGNORED_DIRS in doc_checks.
- fixes #23
=> Doc checks updates

base_checks/check_manifest.py, base_checks/shasum_manifest.sh, open_mpw_prechecker.py
- manifest checks for version control.
- Benchmark is caravel/develop until manifest is merged to master.
=> Manifest checks

base_checks/check_manifest.py, open_mpw_prechecker.py
- add mag/ manifest checks.
- add maglef/ manifest checks.
=> Manifest updates

README.md
Docker command was missing backslash.
=> Fix docker invocation command in README.md

base_checks/check_manifest.py, consistency_checks/consistency_checker.py, consistency_checks/utils/verilog_utils.py
- Add a check for internal power.
- Re-enable external power checks.
=> Power checks

drc_checks/gds_drc_checker.py, drc_checks/magic_drc_check.tcl, drc_checks/run_drc_magic.sh, magic_drc.log, open_mpw_prechecker.py
Reverts efabless/open_mpw_precheck#44
=> Revert "sram abstraction drc"

dependencies/Dockerfile, xor_checks/erase_box.sh, xor_checks/run_xor_checks.sh
Reverts efabless/open_mpw_precheck#53
=> Revert "Efic 78"

checks/manifest_check.py, mpw_precheck.py
- send project, gds, tools, and pdk info as notifications on the platform
=> EF-3239 - Logging Messages Update

checks/tech-files/sky130A_mr.drc
Update MR DECK used by BEOL & FEOL checks
=> EFIC-202 - Update MR DECK used by BEOL & FEOL checks

checks/consistency_check/consistency_check.py, checks/utils/utils.py, dependencies/Dockerfile, mpw_precheck.py
- Revert  `make install` addition
- Misc cleanup steps
- Updated container magic version
=> EF-3306 - Revert `make install` addition and misc updates

checks/utils/utils.py, dependencies/Dockerfile
- Update Caravel commit id to point to mpw-4b tag
- Update Magic to v8.3.245
=> EF-3307 - Caravel and Magic Updates

check_manager/__init__.py
- Magic DRC check temporarily switch to be only a warning
=> EFIC-207 - Magic DRC check no longer counts as a failure

checks/tech-files/sky130A_mr.drc
- Klayout MR Deck updated to 2022.1.13_01.03 release
=> EF-3324 - Update Klayout MR Deck

checks/tech-files/sky130A_mr.drc
- fixed `capm.2b_a` and `cap2m.2b_a`
- added `capm.11` and `cap2m.11`
- fixed `li.6`
- added logs for release and cell exclusion list
=> release 2022.6.22_01.06

README.md, check_manager/__init__.py, checks/drc_checks/klayout/klayout_gds_drc_check.py, checks/drc_checks/magic/magic_drc_check.tcl, checks/drc_checks/magic/magic_gds_drc_check.py, checks/makefile_check.py, checks/tech-files/sky130A.magicrc, dependencies/Dockerfile, docker-mount.sh, mpw_precheck.py, run_precheck.sh
- Log PDK variant as  part of logs
- Replace `PDK_ROOT` argument with `PDK_PATH` that specifies the path down to the PDK variant directory instead of only the ROOT
- Update `magicrc` file to use new `PDK_PATH` argument
- Update `Magic` version to `v8.3.300`
- Update `KLayout` version to `v0.27.9`
- Update `MAKEFILE` check to check for more targets
=> EF-3367 - Support for sky130 variants, cleanup work

checks/drc_checks/klayout/zeroarea.rb.drc, checks/tech-files/sky130A_mr.drc, dependencies/Dockerfile
- Update Zero Area Check to include zero length paths
- Update Magic & KLayout versions
- Update caravel-lite`tag to point to MPW-7
=> EF-3498 - Primary MPW-7 release

dependencies/Dockerfile
- update git version as previous version was archived
=> EF-3498-a 

checks/gpio_defines_check/gpio_defines_check.py
- Typo related to analog designs condition
- Cleanup awkward logging
=> EFIC-257-a | Fix typo related to analog designs

README.md, check_manager/__init__.py, checks/drc_checks/klayout/klayout_gds_drc_check.py, checks/drc_checks/magic/magic_gds_drc_check.py, checks/tech-files/gf180mcuC_mr.drc, checks/tech-files/sky130A.magicrc, debug_precheck.md, dependencies/Dockerfile, mpw_precheck.py
- GF180MCU DRC checks (offgrid, beol, feol)
- Updated pdk info fetching and logging
- Conditional ability for other checks to support GF180MCU
- Fix typo in magic based drc check
=> EF-3614 | Preliminary GF180MCU Support

.gitignore, dependencies/Dockerfile, mpw_precheck.py
- Fix PDK commit get command to handle sky130 projects
- Update Magic version
=> EF-3614-b | fix logging message exception

checks/xor_check/erase_box.tcl
=> fixed erase box coordinates to not trim the pdn ring

checks/license_check/license_check.py, checks/lvs_check/lvs.py
Also added `lvs_results` directory to lvs output hierarchy.
Included `.json` files because they're not set up to include comments.
Should fix #194
=> SPDX-compliance exceptions added.

checks/lvs_check/lvs.py
\+ Added support for hierarchical LVS config files 
\+ Fixed logging issues
\+ Run on a copy of the environment so that the environment doesn't change with the new env variables
=> Support for hierarchical LVS config files 

checks/be_checks/run_be_checks, checks/utils/utils.py
@d-m-bailey Can you please review?
=> changed cvc errors to warnings

check_manager/__init__.py, checks/gpio_defines_check/gpio_defines_check.py, checks/utils/utils.py, checks/xor_check/erase_box_openframe.tcl, checks/xor_check/xor_check.py, mpw_precheck.py
Added support for openframe in precheck. Needs testing.
=> Openframe support

checks/xor_check/erase_box_openframe.tcl
fixed the XOR check to avoid erasing met5 and met4 from outside the PR boundary
=> fixed the XOR check for openframe

checks/drc_checks/magic/magic_drc_check.tcl
=> Fixed SRAM abstraction for DRC

checks/be_checks/run_oeb_check
@d-m-bailey please take a look
=> Update run_oeb_check warning return code

checks/drc_checks/magic/magic_drc_check.tcl, checks/drc_checks/magic/magic_gds_drc_check.py
Corrected the magic startup script reference for the magic DRC check so that it uses the script from the PDK, since everything else also comes from the PDK.
=> Corrected the magic startup script reference for the magic DRC check

checks/be_checks/run_be_checks, checks/be_checks/run_oeb_check, checks/be_checks/tech/sky130A/cvc.power.user_project, checks/be_checks/tech/sky130A/lvs_config.user_project.json, checks/be_checks/tech/sky130B/cvc.power.user_project, checks/be_checks/tech/sky130B/lvs_config.user_project.json
Added cvc power file for mpc user_project
Added lvs_config.json file for mpc user_project
Modified run_be_checks to run CVC on mpc user_project Modified run_oeb_check to work for mpc user_project Modified run_oeb_check to print gpio in order
=> Changes to enable LVS, CVC, and OEB checks on mpc user_projects.

check_manager/__init__.py, checks/illegal_cellname_check/illegal_cellname.py, checks/spike_check/gdsArea0, checks/spike_check/spike.py, checks/topcell_check/topcell.py
\+ Spike check
\+ Illegal cellname check
\+ Topcell check
=> New checks
